### ISSUE TITLE
Authenticate calls should not record request body

### ISSUE THREAD

**Issue by mjirv** [Kable-io/kable-node-express-sdk#5]
Hi! Happy Kable user here. I noticed earlier today that when I use Kable as an authentication provider in express, the request body is being sent to the Kable API.

I noticed this because it caused a problem when the request payload was too large and Kable responded with a 413 error response.

However, in general I also don't think this is desired behavior, since it exposes users' data to a third-party system and as far as I know Kable doesn't need the request body at all. 

Here is the relevant line of code: https://github.com/Kable-io/kable-node-express-sdk/blob/1e53dfb45e9ee8c677ef0f8cb867a6e8c897d6bc/src/index.ts#L245

I am happy to open a PR to fix this if you'd like. Thanks!

**Comment by adamsommer** [comment]
Sure thing @mjirv! Feel free to tag me on a PR 👍
